### PR TITLE
Removed Old CASS Staff

### PR DESCRIPTION
**Pull request by hertelc**
Removed Justin Carr, Kurt Schuff, Beth Sheldon, and Jordan Evans from
the CASS Staff List.

### CODE REVIEW

**Comment by hertelc** [comment]
@Kennric   Please review these changes.  Thanks!

**Comment by hertelc** [comment]
@Kennric @kelnera  - I think Amanda took care of this in another pull request?  Just want to make sure we have it covered.  Thanks!

**Comment by ramereth** [comment]
@hertelc that seems to be the case... when I try to rebase this, it doesn't show the changes.

**Comment by hertelc** [comment]
@ramereth how do I close this out?  Just close and comment button below?

**Comment by ramereth** [comment]
@hertelc yup!

**Comment by hertelc** [comment]
Covered by another pull request.  Closing out this issue.

**Pull request closed without merging**
