### PR TITLE
Slideshow Feature

### LINKED ISSUE #42: Feature request: slideshow
Add a slideshow to the front page, like in OSL and other pages

### PR DESCRIPTION
**Pull request by athai**
Fixes #42.

The problem: ``home.rst`` being saved as *index.html* overwrote the slideshow settings defined in pelicanconf.py. 

Currently, the slideshow is cycling through blog posts (there's only 3) but I think I know how to change what's being featured.  Just need to know what CASS wants to show off on their front page.

## To see the changes in your browser

1. Run ``make html``
2. Run ``make devserver``
3. Visit localhost:8000 in your browser -- if all goes well, you should be able to see the slideshow

Note: Before closing the window, remember to run ``make stopserver`` to stop the local server

@kelnera @Kennric

### CODE REVIEW

**Comment by ramereth** [comment]
@athai this looks good although before this gets merged I think we need to select what we want to show on the slide show. It's showing the current blogs which I think we decided not to do on the CASS page. Is there a way to add static content in for the slide show?

**Comment by kelnera** [comment]
@ramereth I spoke with @athai about this and Rachel is going to send me content to use for the slide show (probably those articles we were talking about earlier). When I get that, I'll work with @athai about how it should look.

**Comment by kelnera** [comment]
@athai These are the featured stories and the order that they're going in from first to last.

Source: http://eecs.oregonstate.edu/feature-stories/impacting-industry
Picture: https://lh4.googleusercontent.com/BUFKzzjcqq2peWObBYMeGNzxUeqRzqCOtdY9-sEI8ghvr_MYd6KJVJIYTrk2v9GuR2jubg=s190

Source: http://oregonstate.edu/ua/ncs/archives/2016/feb/osu-joins-tech-leaders-developing-standard-“internet-things”
Picture: https://lh4.googleusercontent.com/9eVH8QR0Nmy5hEUY1XUkMr2xC5IECwE05oEMUF5qMtv5E-DgAJPxuUJS623tRQ8ZQ0S1xA=s190

Source: http://eecs.oregonstate.edu/feature-stories/oregon-state-at-their-core
Picture: https://lh6.googleusercontent.com/tHG2DyuYhhoKCkkIg_iV-c03a7CCB91PoAr6Y9QkTtYz2bSs40td-6GBgNW4OZ93iXEPHw=s190

Source: http://eecs.oregonstate.edu/feature-stories/saving-lives-with-computer-science
Picture: https://lh3.googleusercontent.com/imPWTrNC_XKcXVQiMFjGcjzcWfUrU-cIUjAqZLvHo_Hd03rUfsTQfuFv29ceyoe6RqmjbA=s190

Source: http://eecs.oregonstate.edu/innovation-engine-revs-up
Picture: https://lh3.googleusercontent.com/G99mWARQYRhXh_tFf0C8vxAQ5aV_VFjKZvXBn3xJwj2Gb56xO8mF6IHDuySc1mLQZ82haw=s190

**Comment by athai** [comment]
Resolved by #65.

**Pull request closed without merging**
