### PR TITLE
Fix organization links in homepage description

### PR DESCRIPTION
**Pull request by athai**
## To test
1. ``make html``
2. ``make devserver``
3. Visit ``localhost:8000`` and click each link

@kelnera @Kennric

### CODE REVIEW

**Comment by Kennric** [comment]
+1

**Comment by alxngyn** [comment]
++

Should it be pointing to staging or is that temporary?

**Comment by athai** [comment]
@alxngyn It's temporary. As of now, those links don't exist on the official CASS site.

**Comment by kelnera** [comment]
+1

**Comment by kelnera** [comment]
@athai Can we get this merged? The name isn't actually going to be changed so we're good on my side of it still doesn't break the site.

**Pull request merged**
