### PR TITLE
Footer address

### PR DESCRIPTION
**Pull request by leian7**
Added email and phone number variables to pelicanconf.py. Addresses issue #46 

Code snippet of what the theme will eventually end up as:
```
<div id='footer'>
  <div class='container'>
    <div class='row'>
      <div class='span2 contact'>
        <h3>Contact Info</h3>
        <div class="content">
          <p>
            {{ SITENAME }}-- {{ NAME_ABBREV }}<br />
            {{ ROOM }} {{ BUILDING }}<br />
            {{ STREET_ADDRESS }}<br />
            {% for email in EMAIL %}
                {% for description, address in email.iteritems() %}
                <span style="color: #C34500;">
                    <a href="mailto:{{ address }}">{{ address }}</a>
                </span><br />
                {% endfor %}
            {% endfor %}
            Phone: {{ PHONE_NUM }}
          </p>
...
```
Screenshot of what the footer will end up looking like:
footer

@athai @kelnera @Kennric @bielenpa @subnomo @alxngyn

### CODE REVIEW

**Comment by alxngyn** [comment]
since we have more than one email, can we make email an array i.e.
```
EMAIL = ['info@CASS.oregonstate.edu', 'email@email2.com']
```

this lets me do this so I can loop through them
```
            {% for e in EMAIL %}
              <span style="color: #C34500;"><a href="mailto:{{ e }}">{{ e }}</a></span><br />
            {% endfor %}
```

**Comment by Kennric** [comment]
@alxngyn @leian7 if we have multiple addresses, they should have names:

```
EMAIL = [{'name': 'OSL Info', 'address': 'info@CASS.oregonstate.edu'}, 
        {'name': 'Another Email', 'address': 'email@email2.com'}]
```

**Comment by Kennric** [comment]
+1

**Comment by alxngyn** [comment]
+1

**Pull request merged**
