### PR TITLE
Sample slideshow

### PR DESCRIPTION
**Pull request by athai**
## Changes in this PR.

- [x] Add ``news`` posts to be featured in slide show
- [x] Add images to accompany news stories
- [x] Move old blog posts to their own directory
- [x] Fix ``All Stories`` button to link to ``News``

The slide show selects its featured stories by (reverse) date. I moved the old blog posts into their own directory so that a story from 2014 can be included in the reel.

## Testing this PR.

1. ``make html``
2. ``make devserver``
3. Visit localhost:8000

To test that the ``All stories`` button works as it should, open a new terminal and:
1. ``cd dougfir-pelican-theme``
2. git checkout thai/all_stories_button
3. Refresh localhost:8000

The ``All stories`` button should then take you to:
news

### Expected Output for the Homepage
slideshow

@ramereth @Kennric @kelnera

### CODE REVIEW

**Comment by cthalmann** [comment]
:+1: really nice!

**Comment by alxngyn** [comment]
+1

**Comment by subnomo** [comment]
Looks good. :+1:

**Comment by kelnera** [comment]
+1 Oh @athai you're such a baller.

**Pull request merged**
